version: "3.5"

services:
  api01: &api
    image: pedrolzoliveira/rinha-de-backend-2024-q1
    hostname: api01
    environment:
      - PORT=3000
      - DB_STRING=postgres://postgres:1234@host.docker.internal/rinha
    ports:
      - "3001:3000"
    depends_on:
      - db
    deploy:
      resources:
        limits:
          cpus: "0.4"
          memory: "150MB"

  api02:
    <<: *api
    hostname: api02
    ports:
      - "3002:3000"
  
  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api01
      - api02
    ports:
      - "9999:9999"
    deploy:
      resources:
        limits:
          cpus: "0.15"
          memory: "50MB"

  db:
    image: postgres:latest
    hostname: db
    environment:
      - POSTGRES_PASSWORD=1234
      - POSTGRES_USER=postgres
      - POSTGRES_DB=rinha
    ports:
      - "5432:5432"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    command: postgres -c checkpoint_timeout=600 -c max_wal_size=4096
    deploy:
      resources:
        limits:
          cpus: "0.55"
          memory: "200MB"

networks:
  default:
    driver: bridge
    name: rinha-nginx-2024q1